In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#Python List vs NumPy Arrays exexution time/performance
import time
size = 10_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python List Time: {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"Numpy Array Time: {end-start} seconds")

Python List Time: 1.1098389625549316 seconds
Numpy Array Time: 0.020374059677124023 seconds


In [6]:
#memory comparison
import sys

print(f"Python list size: {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"Numpy array size: {np_arr.nbytes} bytes")

Python list size: 800000560000000 bytes
Numpy array size: 80000000 bytes


In [8]:
#Creating arrays from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape, arr.dtype)

arr2 = np.array([1, 2, 3, "AIML", "Prime"])
print(arr2, arr2.shape, arr2.dtype)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape, arr2D.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' 'AIML' 'Prime'] (5,) <U21
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3) int64


In [13]:
#Creating arrays using built in methods

arr1 = np.zeros((2, 3), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100) #prefill with value
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 11, 2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [14]:
#Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int64
2


In [15]:
#type conversion
arr = np.array([1, 2, 3, 4, 5])

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[1. 2. 3. 4. 5.] float64
