In [2]:
import numpy as np

In [3]:
#Reshaping array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D to 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [5]:
#Indexing on array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1[0])
print(arr1[3])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[1][1])
print(arr2[0][2])

1
4
5
3


In [6]:
#Fancy indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 2, 4]
print(arr[idx])

[1 3 5]


In [8]:
#Boolean indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [10]:
#Slicing arrays

arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])
print(arr[1:])
print(arr[:3])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3]
[1 2 3 4 5]
[1 3 5]


In [11]:
arr = np.array([1 ,2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[  1 200   3   4   5]


In [12]:
arr = np.array([1 ,2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]
