In [1]:
import numpy as np

In [7]:
#Data Types

arr = np.array([1, 2, 3, 4, 5])  #int
print(arr, arr.dtype)

[1 2 3 4 5] int64


In [8]:
arr = np.array([1, 2, 3, 4, 5, "AIML", "Prime"])  #string
print(arr, arr.dtype)

['1' '2' '3' '4' '5' 'AIML' 'Prime'] <U21


In [9]:
arr = np.array([3 + 5j]) #complex
print(arr, arr.dtype)

arr1 = np.array([3 + 5j])
arr2 = np.array([5 + 3j])
print(arr1 + arr2)
print(arr1 - arr2)

[3.+5.j] complex128
[8.+8.j]
[-2.+2.j]


In [10]:
arr = np.array([{1, 2, 3}, "AIML", 3.14])
print(arr, arr.dtype)

[{1, 2, 3} 'AIML' 3.14] object


In [11]:
#Multi-dimensional arrays & axes

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_cols = np.sum(arr2D, axis = 0)
print(sum_of_cols)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [12]:
#3D array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3D, arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [13]:
#indexing on 3D arrays

print(arr3D[0, 1, 1])
print(arr3D[1, 1, 0])

4
9


In [15]:
#slicing 

print(arr3D[:, 0, :]) # 1st row from both
print(arr3D[:, :, 0]) # 1st col from both

[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [16]:
#replacing values

arr3D[:, 0, :] = 99
print(arr3D) 

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
