In [2]:
import numpy as np

In [5]:
#Vectorization

arr = np.array([1, 2, 3, 4, 5])
print(arr ** 2)
print(arr + 10)

[ 1  4  9 16 25]
[11 12 13 14 15]


In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print(arr1 + arr2)
print(arr1 - arr2)

[6 6 6 6 6]
[-4 -2  0  2  4]


In [7]:
#Brodcasting - (scaling)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[5, 4, 3, 2, 1], [1, 2, 3, 4, 5]])

print(arr1.shape)
print(arr2.shape)
print(arr1 + arr2)

(5,)
(2, 5)
[[ 6  6  6  6  6]
 [ 2  4  6  8 10]]


In [9]:
#normalize

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std = np.std(arr)

print(mean)
print(std)

2.5
1.118033988749895


In [10]:
normalized_arr = (arr - mean) / std

print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
